name: MultipletCombiner
version: 0.0.7
synopsis: A Haskell implementation for combining SU(n) multiplets
description: See README at <https://github.com/mdrslmr/MultipletCombiner>
maintainer: Michael Dressel <michael.dressel@kloenplatz.de>
github: mdrslmr/MultipletCombiner
category: physics,library,science,math,groups

ghc-options: [-dynamic]

extra-source-files:
  - README
  - multiplets.pdf

dependencies:
  - base >= 4.9 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Physics.MultipletCombiner

tests:
  spec:
    main: "MultipletCombinerTests.hs"
    dependencies:
      - base >= 4.9 && < 5
      - HUnit >= 1.6.2.0 && < 2
    source-dirs:
      - src
      - tests
