name: MultipletCombiner
version: 0.0.1
synopsis: A Haskell implementation for combining SU(n) multiplets.
description: See README at <https://github.com/mdrslmr/MultipletCombiner>
maintainer: Michael Dressel <michael.dressel@kloenplatz.de>
github: mdrslmr/MultipletCombiner
category: physics,library,science,math,groups
extra-source-files:
  - README
  - multiplets.pdf

dependencies:
  - base >= 4.15 && < 4.16

library:
  source-dirs: src
  exposed-modules:
    - Physics.MultipletCombiner

tests:
  spec:
    main: "MultipletCombinerTests.hs"
    source-dirs:
      - src
      - tests
